### ISSUE TITLE
Crash - ModuleNotFoundError: No module named 'boto3'

### ISSUE THREAD

**Issue by dezerving** [danny-avila/rag_api#78]
Getting this error after the latest update, container will not start:
```py
Traceback (most recent call last):
  File "/app/main.py", line 46, in <module>
    from psql import PSQLDatabase, ensure_custom_id_index_on_embedding, pg_health_check
  File "/app/psql.py", line 3, in <module>
    from config import DSN, logger
  File "/app/config.py", line 5, in <module>
    import boto3
ModuleNotFoundError: No module named 'boto3'
Traceback (most recent call last):
  File "/app/main.py", line 46, in <module>
    from psql import PSQLDatabase, ensure_custom_id_index_on_embedding, pg_health_check
  File "/app/psql.py", line 3, in <module>
    from config import DSN, logger
  File "/app/config.py", line 5, in <module>
    import boto3
ModuleNotFoundError: No module named 'boto3'
```

**Comment by danny-avila** [comment]
thanks fixing in #79
